### ISSUE TITLE
encoding grayscale jpeg images is broken

### ISSUE THREAD

**Issue by slyrus** [sharplispers/cl-jpeg#13]
The following should make a uniform gray image when test-encode is called:

```
(cl:defpackage :jpeg-test
  (:use #:cl #:jpeg))

(cl:in-package :jpeg-test)

(defun test-image (filename)
  (reduce #'merge-pathnames (list filename "images/")
          :from-end t
          :initial-value (asdf:component-pathname
                          (asdf:find-system "cl-jpeg"))))

(ensure-directories-exist (output-image ""))

(defparameter *gray-q-tabs* (vector jpeg::+q-luminance+))

(defun test-encode (&optional (output (test-image "simple.jpeg")))
  (let ((width 32)
        (height 32))
    (let ((buf (make-array (* width height) :initial-element 42)))
      (time (encode-image output buf 1 width height
                          :q-tabs *gray-q-tabs*)))))
```

This should give a uniform gray image, but doesn't.

**Comment by varjagg** [comment]
Thanks, hope to be able look into this by Friday.

**Comment by varjagg** [comment]
You can try now.

**Comment by slyrus** [comment]
Fixed, thanks!

**Comment by fragrans** [comment]
Could you guys please also sync it to Quicklisp repository? It is still broken there.

**Comment by varjagg** [comment]
I believe Quicklisp is release-based, so we have to wait until the next general update.
